apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: python-demo
  policy:
    numerical:
      order: asc # asc bedeutet: die höchste Nummer gewinnt (z.B. 33 > 32)
  filter:
    pattern: '^build-(?P<tag>\d+)' # Sucht nach "build-" gefolgt von Zahlen
