apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  filterTags:
    pattern: '^build-(?P<build>\d+)$'
    extract: '$build'
  policy:
    numerical:
      order: desc
  imageRepositoryRef:
    name: python-demo