apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  filterTags:
    pattern:  '^build-(?P<build>\d+)$' # Einfacher Filter: Startet mit build-, gefolgt von Zahlen
    extract: '$build'
  policy:
    numerical:
      order: asc
  imageRepositoryRef:
    name: python-demo
